# Generated by Django 3.2.18 on 2023-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(max_length=90)),
                ('proveedor_estado', models.BooleanField(default=True)),
            ],
        ),
    ]
