# Generated by Django 3.2.18 on 2023-02-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productos_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='proveedor',
        ),
    ]
